-- Insert sample World Cup teams
INSERT INTO teams ("name", division_id, division, flag_url, team_type, code) VALUES
('England',1,'British','https://upload.wikimedia.org/wikipedia/en/b/be/Flag_of_England.svg','national','ENG'),
('Scotland',1,'British','https://upload.wikimedia.org/wikipedia/commons/1/10/Flag_of_Scotland.svg','national','SCO'),
('Wales',1,'British','https://upload.wikimedia.org/wikipedia/commons/d/dc/Flag_of_Wales.svg','national', 'WAL'),
('Republic of Ireland',1,'British','https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg','national','IRL'),
('Northern Ireland',1,'British','https://upload.wikimedia.org/wikipedia/commons/6/63/Flag_of_Northern_Ireland_%281924%E2%80%931953%29.svg','national','NIR'),
('Gibraltar',1,'British','https://upload.wikimedia.org/wikipedia/commons/0/02/Flag_of_Gibraltar.svg','national','GIB'),
('Iceland',2,'Nordic','https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg','national','ISL'),
('Faroe Islands',2,'Nordic','https://upload.wikimedia.org/wikipedia/commons/3/3c/Flag_of_the_Faroe_Islands.svg','national','FRO'),
('Norway',2,'Nordic','https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg','national','NOR'),
('Sweden',2,'Nordic','https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg','national','SWE'),
('Denmark',2,'Nordic','https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg','national','DEN'),
('Finland',2,'Nordic','https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg','national','FIN'),
('Lithuania',2,'Nordic','https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg','national','LTU'),
('Latvia',2,'Nordic','https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg','national','LVA'),
('Estonia',2,'Nordic','https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg','national','EST'),
('Greenland',2,'Nordic','https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_Greenland.svg','national','GRL'),
('France',3,'Western Europe','https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg','national','FRA'),
('Belgium',3,'Western Europe','https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg','national','BEL'),
('Netherlands',3,'Western Europe','https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg','national','NED'),
('Luxembourg',3,'Western Europe','https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Luxembourg.svg','national','LUX'),
('Monaco',3,'Western Europe','https://upload.wikimedia.org/wikipedia/commons/e/ea/Flag_of_Monaco.svg','national','MON'),
('Andorra',3,'Western Europe','https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Andorra.svg','national','AND'),
('Italy',4,'Southern Europe','https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg','national','ITA'),
('Spain',4,'Southern Europe','https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg','national','ESP'),
('Portugal',4,'Southern Europe','https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg','national','POR'),
('San Marino',4,'Southern Europe','https://upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_San_Marino.svg','national','SMR'),
('Vatican City',4,'Southern Europe','https://upload.wikimedia.org/wikipedia/commons/b/b3/Flag_of_Vatican_City_%282023%E2%80%93present%29.svg','national','VAT'),
('Malta',4,'Southern Europe','https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Malta.svg','national','MLT'),
('Germany',5,'Central Europe','https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg','national','GER'),
('Austria',5,'Central Europe','https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg','national','AUT'),
('Switzerland',5,'Central Europe','https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg','national','SUI'),
('Liechtenstein',5,'Central Europe','https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Liechtenstein.svg','national','LIE'),
('Czech Republic',5,'Central Europe','https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg','national','CZE'),
('Slovakia',5,'Central Europe','https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg','national','SVK'),
('Hungary',5,'Central Europe','https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg','national','HUN'),
('Poland',5,'Central Europe','https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg','national','POL'),
('Slovenia',6,'Balkans','https://upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Slovenia.svg','national','SLO'),
('Croatia',6,'Balkans','https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg','national','CRO'),
('Bosnia and Herzegovina',6,'Balkans','https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg','national','BIH'),
('Serbia',6,'Balkans','https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg','national','SRB'),
('Montenegro',6,'Balkans','https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Montenegro.svg','national','MNE'),
('North Macedonia',6,'Balkans','https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_North_Macedonia.svg','national','MKD'),
('Albania',6,'Balkans','https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg','national','ALB'),
('Kosovo',6,'Balkans','https://upload.wikimedia.org/wikipedia/commons/1/1f/Flag_of_Kosovo.svg','national','KOS'),
('Bulgaria',7,'Eastern Europe','https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg','national','BUL'),
('Romania',7,'Eastern Europe','https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg','national','ROM'),
('Moldova',7,'Eastern Europe','https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Moldova.svg','national','MDA'),
('Ukraine',7,'Eastern Europe','https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg','national','UKR'),
('Belarus',7,'Eastern Europe','https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Belarus.svg','national','BLR'),
('Russia',7,'Eastern Europe','https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg','national','RUS'),
('Armenia',8,'Southeastern Europe','https://upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Armenia.svg','national','ARM'),
('Azerbaijan',8,'Southeastern Europe','https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg','national','AZE'),
('Georgia',8,'Southeastern Europe','https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Georgia.svg','national','GEO'),
('Greece',8,'Southeastern Europe','https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg','national','GRE'),
('Israel',8,'Southeastern Europe','https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg','national','ISR'),
('Turkey',8,'Southeastern Europe','https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg','national','TUR'),
('Cyprus',8,'Southeastern Europe','https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg','national','CYP'),
('Northern Cyprus',8,'Southeastern Europe','https://upload.wikimedia.org/wikipedia/commons/1/1e/Flag_of_the_Turkish_Republic_of_Northern_Cyprus.svg','national','NCYP'),
('Abkhazia',8,'Southeastern Europe','https://upload.wikimedia.org/wikipedia/commons/7/7a/Flag_of_the_Republic_of_Abkhazia.svg','national','ABK'),
('South Ossetia',8,'Southeastern Europe','https://upload.wikimedia.org/wikipedia/commons/1/12/Flag_of_South_Ossetia.svg','national','SOS'),
('Artsakh',8,'Southeastern Europe','https://upload.wikimedia.org/wikipedia/commons/3/3d/Flag_of_Artsakh.svg','national','ART')