INSERT INTO teams ("name", division_id, division, flag_url, team_type, code) VALUES
('United States',9,'North America','https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg','national','USA'),
('Canada',9,'North America','https://upload.wikimedia.org/wikipedia/en/c/cf/Flag_of_Canada.svg','national','CAN'),
('Mexico',9,'North America','https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg','national','MEX'),
('Bermuda',9,'North America','https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bermuda.svg','national','BMU'),
('US Virgin Islands',9,'North America','https://upload.wikimedia.org/wikipedia/commons/f/f8/Flag_of_the_United_States_Virgin_Islands.svg','national','VIR'),
('Turks and Caicos Islands',9,'North America','https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_the_Turks_and_Caicos_Islands.svg','national','TCA'),
('Belize',10,'Central America','https://upload.wikimedia.org/wikipedia/commons/e/e7/Flag_of_Belize.svg','national','BLZ'),
('Honduras',10,'Central America','https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Honduras_%282022-%29.svg','national','HND'),
('Guatemala',10,'Central America','https://upload.wikimedia.org/wikipedia/commons/e/ec/Flag_of_Guatemala.svg','national','GTM'),
('El Salvador',10,'Central America','https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_El_Salvador.svg','national','SLV'),
('Nicaragua',10,'Central America','https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Nicaragua.svg','national','NIC'),
('Costa Rica',10,'Central America','https://upload.wikimedia.org/wikipedia/commons/f/f2/Flag_of_Costa_Rica.svg','national','CRI'),
('Panama',10,'Central America','https://upload.wikimedia.org/wikipedia/commons/a/ab/Flag_of_Panama.svg','national','PAN'),
('Puerto Rico',11,'Greater Antilles','https://upload.wikimedia.org/wikipedia/commons/2/28/Flag_of_Puerto_Rico.svg','national','PUR'),
('Cuba',11,'Greater Antilles','https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg','national','CUB'),
('Bahamas',11,'Greater Antilles','https://upload.wikimedia.org/wikipedia/commons/9/93/Flag_of_the_Bahamas.svg','national','BHS'),
('Cayman Islands',11,'Greater Antilles','https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_the_Cayman_Islands.svg','national','CYM'),
('Dominican Republic',11,'Greater Antilles','https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg','national','DOM'),
('Haiti',11,'Greater Antilles','https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg','national','HTI'),
('Jamaica',11,'Greater Antilles','https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg','national','JAM'),
('Aruba',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Aruba.svg','national','ABW'),
('Bonaire',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/1/1e/Flag_of_Bonaire.svg','national','BES'),
('Curacao',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_Cura%C3%A7ao.svg','national','CUW'),
('Anguilla',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Anguilla.svg','national','AIA'),
('Antigua and Barbuda',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Antigua_and_Barbuda.svg','national','ATG'),
('Barbados',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Barbados.svg','national','BRB'),
('British Virgin Islands',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/4/42/Flag_of_the_British_Virgin_Islands.svg','national','VGB'),
('Dominica',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Dominica.svg','national','DMA'),
('French Guiana',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_French_Guiana.svg','national','GUF'),
('Grenada',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Grenada.svg','national','GRD'),
('Guadeloupe',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/e/e7/Unofficial_flag_of_Guadeloupe_%28local%29.svg','national','GLP'),
('Guyana',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_Guyana.svg','national','GUY'),
('Martinique',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/2/27/Flag-of-Martinique.svg','national','MTQ'),
('Montserrat',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Montserrat.svg','national','MSR'),
('Saint Kitts and Nevis',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg','national','KNA'),
('Saint Lucia',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Saint_Lucia.svg','national','LCA'),
('Saint Martin',12,'Carribean','https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg','national','MAF'),
('Saint Vincent and the Grenadines',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg','national','VCT'),
('Sint Marteen',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Sint_Maarten.svg','national','SXM'),
('Saint Barthelemy',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/e/e7/Flag_of_Saint_Barth%C3%A9lemy_%28Local%29.svg','national','BL'),
('Saint Pierre and Miquelon',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_Saint-Pierre_and_Miquelon.svg','national','SPM'),
('Sint Eustatius',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_Sint_Eustatius.svg','national','STE'),
('Suriname',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/6/60/Flag_of_Suriname.svg','national','SUR'),
('Trinidad and Tobago',12,'Carribean','https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Trinidad_and_Tobago.svg','national','TTO'),
('Argentina',13,'South America','https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg','national','ARG'),
('Bolivia',13,'South America','https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Bolivia.svg','national','BOL'),
('Brazil',13,'South America','https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg','national','BRA'),
('Chile',13,'South America','https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg','national','CHL'),
('Colombia',13,'South America','https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg','national','COL'),
('Ecuador',13,'South America','https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg','national','ECU'),
('Paraguay',13,'South America','https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Paraguay.svg','national','PRY'),
('Peru',13,'South America','https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Peru.svg','national','PER'),
('Uruguay',13,'South America','https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg','national','URY'),
('Venezuela',13,'South America','https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Venezuela.svg','national','VEN')
