INSERT INTO teams ("name", division_id, division, flag_url, team_type, code) VALUES
('Australia',14,'Oceania','https://upload.wikimedia.org/wikipedia/en/b/b9/Flag_of_Australia.svg','national','AUS'),
('New Zealand',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg','national','NZL'),
('Papua New Guinea',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/e/e3/Flag_of_Papua_New_Guinea.svg','national','PNG'),
('Fiji',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Fiji.svg','national','FJI'),
('Solomon Islands',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Solomon_Islands.svg','national','SLB'),
('Samoa',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Samoa.svg','national','WSM'),
('Tonga',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Tonga.svg','national','TON'),
('Kiribati',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kiribati.svg','national','KIR'),
('Tahiti',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/d/db/Flag_of_French_Polynesia.svg','national','TAH'),
('Tuvalu',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tuvalu.svg','national','TUV'),
('Vanuatu',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/6/6e/Flag_of_Vanuatu_%28official%29.svg','national','VUT'),
('Nauru',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/3/30/Flag_of_Nauru.svg','national','NRU'),
('New Caledonia',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_FLNKS.svg','national','NCL'),
('Wallis and Futuna',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/d/d2/Flag_of_Wallis_and_Futuna.svg','national','WLF'),
('American Samoa',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/8/87/Flag_of_American_Samoa.svg','national','ASM'),
('Cook Islands',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/3/35/Flag_of_the_Cook_Islands.svg','national','COK'),
('Niue',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Niue.svg','national','NIU'),
('Micronesia',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg','national','FSM'),
('Marshall Islands',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/2/2e/Flag_of_the_Marshall_Islands.svg','national','MHL'),
('Palau',14,'Oceania','https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Palau.svg','national','PLW'),
('Brunei Darussalam',15,'Southeast Asia','https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Brunei.svg','national','BRN'),
('Cambodia',15,'Southeast Asia','https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Cambodia.svg','national','CAM'),
('East Timor',15,'Southeast Asia','https://upload.wikimedia.org/wikipedia/commons/2/26/Flag_of_East_Timor.svg','national','TLS'),
('Indonesia',15,'Southeast Asia','https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg','national','IDN'),
('Laos',15,'Southeast Asia','https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Laos.svg','national','LAO'),
('Malaysia',15,'Southeast Asia','https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg','national','MYS'),
('Myanmar',15,'Southeast Asia','https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Myanmar.svg','national','MMR'),
('Philippines',15,'Southeast Asia','https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg','national','PHL'),
('Singapore',15,'Southeast Asia','https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg','national','SGP'),
('Thailand',15,'Southeast Asia','https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg','national','THA'),
('Vietnam',15,'Southeast Asia','https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg','national','VNM'),
('Northern Mariana Islands',16,'East Asia','https://upload.wikimedia.org/wikipedia/commons/0/0b/Flag_of_the_Northern_Mariana_Islands.svg','national','MNP'),
('China PR',16,'East Asia','https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg','national','CHN'),
('Hong Kong',16,'East Asia','https://upload.wikimedia.org/wikipedia/commons/5/5b/Flag_of_Hong_Kong.svg','national','HKG'),
('Japan',16,'East Asia','https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg','national','JPN'),
('Macau',16,'East Asia','https://upload.wikimedia.org/wikipedia/commons/6/63/Flag_of_Macau.svg','national','MAC'),
('Mongolia',16,'East Asia','https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Mongolia.svg','national','MNG'),
('North Korea',16,'East Asia','https://upload.wikimedia.org/wikipedia/commons/5/51/Flag_of_North_Korea.svg','national','PRK'),
('South Korea',16,'East Asia','https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg','national','KOR'),
('Taiwan',16,'East Asia','https://upload.wikimedia.org/wikipedia/commons/7/72/Flag_of_the_Republic_of_China.svg','national','TPE'),
('Guam',16,'East Asia','https://upload.wikimedia.org/wikipedia/commons/0/07/Flag_of_Guam.svg','national','GUM'),
('Hmong',16,'East Asia','https://upload.wikimedia.org/wikipedia/commons/0/0f/Hmong_Flag_%28UNPO%29.svg','national','HMO'),
('Bangladesh',17,'South Asia','https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg','national','BGD'),
('Bhutan',17,'South Asia','https://upload.wikimedia.org/wikipedia/commons/9/91/Flag_of_Bhutan.svg','national','BTN'),
('India',17,'South Asia','https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg','national','IND'),
('Maldives',17,'South Asia','https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Maldives.svg','national','MDV'),
('Nepal',17,'South Asia','https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg','national','NPL'),
('Pakistan',17,'South Asia','https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg','national','PAK'),
('Sri Lanka',17,'South Asia','https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg','national','LKA'),
('Afghanistan',18,'Central Asia','https://upload.wikimedia.org/wikipedia/commons/c/cd/Flag_of_Afghanistan_%282013%E2%80%932021%29.svg','national','AFG'),
('Iran',18,'Central Asia','https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg','national','IRN'),
('Kazakhstan',18,'Central Asia','https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg','national','KAZ'),
('Kyrgyzstan',18,'Central Asia','https://upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Kyrgyzstan.svg','national','KGZ'),
('Tajikistan',18,'Central Asia','https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Tajikistan.svg','national','TJK'),
('Turkmenistan',18,'Central Asia','https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Turkmenistan.svg','national','TKM'),
('Uzbekistan',18,'Central Asia','https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Uzbekistan.svg','national','UZB'),
('Bahrain',19,'Middle East','https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg','national','BHR'),
('Iraq',19,'Middle East','https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Iraq.svg','national','IRQ'),
('Jordan',19,'Middle East','https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg','national','JOR'),
('Kuwait',19,'Middle East','https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Kuwait.svg','national','KWT'),
('Lebanon',19,'Middle East','https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg','national','LBN'),
('Oman',19,'Middle East','https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Oman.svg','national','OMN'),
('Palestine',19,'Middle East','https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Palestine.svg','national','PSE'),
('Qatar',19,'Middle East','https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg','national','QAT'),
('Saudi Arabia',19,'Middle East','https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg','national','SAU'),
('Syria',19,'Middle East','https://upload.wikimedia.org/wikipedia/commons/5/54/Flag_of_Syria_%282025-%29.svg','national','SYR'),
('United Arab Emirates',19,'Middle East','https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg','national','ARE'),
('Yemen',19,'Middle East','https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Yemen.svg','national','YEM'),
('Syrian Arab Republic',19,'Middle East','https://upload.wikimedia.org/wikipedia/commons/e/e1/Flag_of_the_United_Arab_Republic_%281958%E2%80%931971%29%2C_Flag_of_Syria_%281980%E2%80%932024%29.svg','national','SYR-AR')