INSERT INTO teams ("name", division_id, division, flag_url, team_type, code) VALUES
('Egypt',20,'North Africa','https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg','national','EGY'),
('Libya',20,'North Africa','https://upload.wikimedia.org/wikipedia/commons/0/05/Flag_of_Libya.svg','national','LBY'),
('Morocco',20,'North Africa','https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg','national','MAR'),
('Sudan',20,'North Africa','https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Sudan.svg','national','SDN'),
('Tunisia',20,'North Africa','https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg','national','TUN'),
('Algeria',20,'North Africa','https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg','national','DZA'),
('Mauritania',20,'North Africa','https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Mauritania.svg','national','MRT'),
('Benin',21,'West Africa','https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Benin.svg','national','BEN'),
('Burkina Faso',21,'West Africa','https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Burkina_Faso.svg','national','BFA'),
('Cape Verde',21,'West Africa','https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Cape_Verde.svg','national','CPV'),
('Cote dIvoire',21,'West Africa','https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg','national','CIV'),
('Gambia',21,'West Africa','https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_The_Gambia.svg','national','GMB'),
('Ghana',21,'West Africa','https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg','national','GHA'),
('Guinea',21,'West Africa','https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Guinea.svg','national','GIN'),
('Guinea-Bissau',21,'West Africa','https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Guinea-Bissau.svg','national','GNB'),
('Liberia',21,'West Africa','https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Liberia.svg','national','LBR'),
('Mali',21,'West Africa','https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Mali.svg','national','MLI'),
('Niger',21,'West Africa','https://upload.wikimedia.org/wikipedia/commons/f/f4/Flag_of_Niger.svg','national','NER'),
('Nigeria',21,'West Africa','https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg','national','NGA'),
('Senegal',21,'West Africa','https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Senegal.svg','national','SEN'),
('Sierra Leone',21,'West Africa','https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Sierra_Leone.svg','national','SLE'),
('Togo',21,'West Africa','https://upload.wikimedia.org/wikipedia/commons/6/68/Flag_of_Togo.svg','national','TGO'),
('Cameroon',22,'Central Africa','https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg','national','CMR'),
('Central African Republic',22,'Central Africa','https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Central_African_Republic.svg','national','CAF'),
('Chad',22,'Central Africa','https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Chad.svg','national','TCD'),
('Congo',22,'Central Africa','https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_the_Republic_of_the_Congo.svg','national','COG'),
('Democratic Republic of the Congo',22,'Central Africa','https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg','national','COD'),
('Equatorial Guinea',22,'Central Africa','https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Equatorial_Guinea.svg','national','GNQ'),
('Gabon',22,'Central Africa','https://upload.wikimedia.org/wikipedia/commons/0/04/Flag_of_Gabon.svg','national','GAB'),
('Sao Tome and Principe',22,'Central Africa','https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe.svg','national','STP'),
('Burundi',23,'East Africa','https://upload.wikimedia.org/wikipedia/commons/5/50/Flag_of_Burundi.svg','national','BDI'),
('Djibouti',23,'East Africa','https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_Djibouti.svg','national','DJI'),
('Eritrea',23,'East Africa','https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Eritrea.svg','national','ERI'),
('Ethiopia',23,'East Africa','https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Ethiopia.svg','national','ETH'),
('Kenya',23,'East Africa','https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg','national','KEN'),
('Rwanda',23,'East Africa','https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Rwanda.svg','national','RWA'),
('Somalia',23,'East Africa','https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Somalia.svg','national','SOM'),
('South Sudan',23,'East Africa','https://upload.wikimedia.org/wikipedia/commons/7/7a/Flag_of_South_Sudan.svg','national','SSD'),
('Tanzania',23,'East Africa','https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tanzania.svg','national','TZA'),
('Uganda',23,'East Africa','https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Uganda.svg','national','UGA'),
('Zanzibar',23,'East Africa','https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Zanzibar.svg','national','ZNZ'),
('Angola',24,'Southern Africa','https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Angola.svg','national','AGO'),
('Botswana',24,'Southern Africa','https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Botswana.svg','national','BWA'),
('Eswatini',24,'Southern Africa','https://upload.wikimedia.org/wikipedia/commons/f/fb/Flag_of_Eswatini.svg','national','SWZ'),
('Comoros',24,'Southern Africa','https://upload.wikimedia.org/wikipedia/commons/9/94/Flag_of_the_Comoros.svg','national','COM'),
('Lesotho',24,'Southern Africa','https://upload.wikimedia.org/wikipedia/commons/4/4a/Flag_of_Lesotho.svg','national','LSO'),
('Madagascar',24,'Southern Africa','https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Madagascar.svg','national','MDG'),
('Malawi',24,'Southern Africa','https://upload.wikimedia.org/wikipedia/commons/d/d1/Flag_of_Malawi.svg','national','MWI'),
('Mauritius',24,'Southern Africa','https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Mauritius.svg','national','MUS'),
('Mozambique',24,'Southern Africa','https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Mozambique.svg','national','MOZ'),
('Namibia',24,'Southern Africa','https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Namibia.svg','national','NAM'),
('Seychelles',24,'Southern Africa','https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Seychelles.svg','national','SYC'),
('South Africa',24,'Southern Africa','https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg','national','ZAF'),
('Zambia',24,'Southern Africa','https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Zambia.svg','national','ZMB'),
('Zimbabwe',24,'Southern Africa','https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg','national','ZWE')